---
title: "Mini-Project 2"
author: "Grace Hartley, Amrita Acharya, Callie Slevin"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---

^[https://github.com/hartlegr/sds192-mp2]

```{r, message=FALSE}
library(tidyverse)
library(extrafont)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
#devtools::install_github("benmarwick/wordcountaddin")


 #Word count: `r wordcountaddin::word_count()'

```


```{r}
cand_contrib <- candidates%>% 
  left_join(contributions, "cand_id")
```

We first filtered xyz... 
```{r, message=FALSE, eval=FALSE}
cand_contrib%>%
  filter(cand_election_yr == 2012)%>% 
  filter(cand_ici== "I")%>%
  group_by(cand_id, cand_name)%>%
  summarize(total_cont = sum(transaction_amt, na.rm = TRUE))
  
  

```

```{r, eval=FALSE}
ron_kind <- candidates %>%
  filter(cand_name == "KIND, RON")
```

```{r, eval=FALSE}
library(Stat2Data)
tally(~transaction_type, data = cand_contrib)
```

Then, we...
```{r}
cand_contrib <- cand_contrib%>%
  filter(cand_election_yr == 2012)%>% 
  na.omit() %>%
  group_by(transaction_type)%>%
  mutate(for_cand = ifelse(transaction_type == "24K"|transaction_type ==  "24E", "forcan","agcan"))
 
```

The last part of the data wrangling process included...
```{r, message=FALSE, warning=FALSE}
contrib_for <- cand_contrib %>%
  filter(!is.na("for_cand"))%>%
  filter(for_cand == "forcan")
 

contrib_ag <- cand_contrib %>%
  filter(for_cand == "agcan")%>%
  filter(!is.na("ag_cand"))
```

```{r, warning=FALSE, eval=FALSE}

boxplot <- ggplot(cand_contrib, aes(for_cand, log10(transaction_amt))) + geom_boxplot(color = "cornflowerblue")
boxplot
```

```{r, warning=FALSE, eval=FALSE}
contrib_forplot <- ggplot(contrib_for, aes(x = cand_ici, log10(transaction_amt))) + geom_boxplot()

contrib_forplot

contrib_foragplot <- ggplot(cand_contrib, aes(x = cand_ici, log10(transaction_amt))) + geom_boxplot(color = "cornflowerblue") + facet_wrap(~for_cand) 

contrib_foragplot
```

```{r, eval=FALSE}
library(ggthemes)
contrib_forplot <- ggplot(contrib_for, aes(x = cand_ici), log10(transaction_amt)) + geom_bar()

contrib_forplot
```


```{r}
labels<-c(agcan="Against Canidate", forcan="For Canidate")

```

```{r}
library(ggthemes)
contrib_foragplot <- ggplot(cand_contrib, aes(x = cand_ici), transaction_amt) + geom_bar( fill = "darkgoldenrod1") + facet_wrap(~for_cand, labeller=labeller(for_cand=labels)) +
  theme_economist()+
  xlab("")+
  scale_x_discrete(labels=c("Challenger", "Incumbent", "Open Seat"))+
  ylab("Total contributions (US $)")

contrib_foragplot
```


Generalized function:
```{r}
contrib_any_year<-function(year){
  cand_contrib_yearly<-cand_contrib%>%
  filter(cand_election_yr == year)%>% 
  na.omit() %>%
  group_by(transaction_type)%>%
  mutate(for_cand = ifelse(transaction_type == "24K"|transaction_type ==  "24E", "forcan","agcan"))
  
  cand_contrib_yearly
  
  contrib_foragplot <- ggplot(cand_contrib_yearly, aes(x = cand_ici), transaction_amt) + geom_bar( fill = "darkgoldenrod1") + facet_wrap(~for_cand, labeller=labeller(for_cand=labels)) +
  theme_economist()+
  xlab("")+
  scale_x_discrete(labels=c("Challenger", "Incumbent", "Open Seat"))+
  ylab("Total contributions (US $)")

contrib_foragplot
}
```


```{r}
years<-c(1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014)

contrib_any_year(2004)
```

^ why does this only work in 2012?
Graphic(s) + analysis:

